### ISSUE TITLE
Footer in submission template

### ISSUE THREAD

**Issue by kozaka93** [automl-conf/LatexTemplate#11]
Hi, 

The conference submission template has a footer that includes the year of the last conference. I think that it should be changed from "Submitted to AutoML Conference 2022" to "2023". 

Best,
Anna

**Comment by rmgarnett** [comment]
I believe you may have an old version of the template:

https://github.com/automl-conf/LatexTemplate/blob/15c9fa31fe43830f32c396406fb80fda620fab53/automl.sty#L13

**Comment by kozaka93** [comment]
Thank you. It is possible that I have an old version, sorry.
