### ISSUE TITLE
Email command for author list

### ISSUE THREAD

**Issue by nabenabe0928** [automl-conf/LatexTemplate#15]
I read `automl.sty`, but I could not find email commands.
How can I do to make my paper look like this or would you be able to add a command for this?

![image](https://github.com/automl-conf/LatexTemplate/assets/47781922/8dff89a5-2273-4769-802f-a0768e4a81a7)

**Comment by rmgarnett** [comment]
The example you give is not correctly formatted. The correct mechanism for adding an author/email, as listed in `instructions.tex` is:

````
% The syntax for adding an author is
%
% \author[i]{\nameemail{author name}{author email}}
````

The email will not be visible in the PDF but instead a `mailto:` link will be created for the author's name.
