### ISSUE TITLE
Abstract Submission Format

### ISSUE THREAD

**Issue by SatenderGunwal** [automl-conf/LatexTemplate#3]
Just wanted to confirm that in the abstract submission, we only need to submit the abstract with the paper heading under anonymous authorship, and no other sections are required.

**Comment by mlindauer** [comment]
Hi, you don't need to submit any pdf for the abstract deadline. Please go to https://openreview.net/group?id=automl.cc/AutoML/2022/Track/Main and fill out the required fields; this includes paper title, abstract and list of authors. The latter won't be visible for the reviewers.
