### ISSUE TITLE
ABCD track footer

### ISSUE THREAD

**Issue by joaquinvanschoren** [automl-conf/LatexTemplate#6]
For the ABCD track, we need a version of the template that is identical except for the footer.
Should I enable this by adding an option in the main style file?
Or should I create an entirely new version of the template?

Thanks!

**Comment by joaquinvanschoren** [comment]
Ping :)

**Comment by joaquinvanschoren** [comment]
Hi, any answer here? A brief one will do so I know how to move ahead. We'll need this very soon.

**Comment by jacobrgardner** [comment]
@joaquinvanschoren What are the total changes you'd want to the document? Just the footer to indicate the track like the current workshop track does? If so, I think we can handle that the same way as with the current workshop track argumt.

**Comment by joaquinvanschoren** [comment]
Yes, pretty much. Ok, I'll do it that way then. Shall I create a PR?

**Comment by jacobrgardner** [comment]
Yeah, go ahead and open a PR, or I can do it if you'd prefer. If all that's changing is the footer we can get it merged quickly.

**Comment by joaquinvanschoren** [comment]
If you have time, please do it. You can probably do it 5 times faster than me :). Happy to check later.

**Comment by jacobrgardner** [comment]
Alright, I'll get a draft done today 👍
